### ISSUE TITLE
When gridding fails it does so in an unexpected direction

### ISSUE THREAD

**Issue by local-minimum** [Scan-o-Matic/scanomatic#138]
In the few cases that gridding fails, it has a tenancy/bias to do so excluding the signals that should have been most reliable.

**Comment by skymandr** [comment]
I think that the description of this issue is not correct. The gridding algorithm works as best it can, but the image is very hard to grid correctly, so the offset that is needed as input from the user varies a little.

Here is an image with no correction applied:
![gridding_right_correction_none](https://user-images.githubusercontent.com/358614/27859619-a6719fde-6179-11e7-8d67-2979ba29efb8.png)

a correction of `(3, 0)` would solve the issue:
![gridding_right_correction_ 3 0](https://user-images.githubusercontent.com/358614/27859626-aabdf1fa-6179-11e7-8d6a-f34ea6b77997.png)

but sometimes (perhaps even most of the time), the gridding needs a correction factor of `(4, 0)`:
![gridding_wrong_correction_none](https://user-images.githubusercontent.com/358614/27859668-c899aed0-6179-11e7-9189-6e95a2fdf7f9.png)

That the results are random/unpredictable is certainly a problem, but it appears that the algorithm
works in that it finds the strongest signals - that it looked otherwise is probably a coordinate mixup in the UI.

**Comment by skymandr** [comment]
I think that without heuristics this problem can never be completely solved, but I have some ideas on how the algorithm can be made more stable. (There is off course nothing inherently wrong in also applying heuristics, as long as we can make ourselves reasonably convinced that we don't introduce new artifacts.)

**Comment by local-minimum** [comment]
How about something like:

```
IF several near equally good options
ADD cost for each cell grid position outside the image
WEIGHT result based on grid-center to image center distance
```

**Comment by skymandr** [comment]
I suggest we close this one and open a new issue for making gridding more stable (or use #70).

**Comment by local-minimum** [comment]
Let's use #70
