### ISSUE TITLE
How should we work with Scan-o-matic versions?

### ISSUE THREAD

**Issue by skymandr** [Scan-o-Matic/scanomatic#249]
Scan-o-matic uses a versioning [[0]] system with three digits, at the time of writing 2.2.0. This looks like semantic versioning [[1]], but is not used quite that way. Currently the version isn't updated in a structured way, so it isn't clear what versions mean, when the developer should bump it or which digit to bump. The aim of this issue is to have a discussion on this. Hopefully the outcome will be some sort of guidelines for how to work with versioning in development, which can also hopefully be of use for future users maintaining Scan-o-matic instances at their lab. 

[0]: https://github.com/Scan-o-Matic/scanomatic/blob/master/scanomatic/__init__.py
[1]: https://semver.org/

**Comment by skymandr** [comment]
What I want most is to know what to update, how and when. My opinion is that adopting semver more or less directly would be the easiest and most transparent solution. This would probably be a break with what major releases have meant before (I'll call them "Milestones", for want of a better word), but to me being in line with the standards for python code [[0]] would be worth that. A new way of denoting and releasing "milestones" would then perhaps be needed. This would be my preferred solution, but as indicated above the main thing is that we have some form of agreed upon standard to relate to.

[0]: https://packaging.python.org/tutorials/distributing-packages/#choosing-a-versioning-scheme

**Comment by local-minimum** [comment]
It isn't semantic versioning, that it looks like it kind of isn't an argument to me.
It is updated in a semi-structured way, it just isn't regularly updated. 

**Q1: Should we have versions in the code?**

**Q2: Should we have another system?**

Structure has been (again, not really anything to do with semver system):

`MAJOR`.`MINOR`.`PATCH`.

`MAJOR` signifies that comparison of **data** from analysis and feature extraction should not be done. It has nothing to do with API or interface. It can be used to celebrate things like publications.
`MINOR` is introduction of a notable feature, typically not relating to API, but to UI.
`PATCH` is increased by each PR to master or more often (could be each commit in PR or even several steps in a single commit). This is because changing the version invalidates all UI content in user cache.

I'm open to changes to that system. Or working towards excluding versioning from the code. Note that if we change system and it doesn't support version change per PR we need to first make overhaul of the UI _and_ implement invalidation of cache.

**Q3: Should we have any system in the code**

Having code changes show new versions is bad because two concurrent devs will clash on what their versions are. Versioning should be automatic and handled in the PR process.

**Comment by skymandr** [comment]
I'm mostly happy with those guidelines! Though I feel that celebrating publications should at least not play a defining role in versioning, breaking data backwards compatibility seems like a good analogue to semver's Major preconditions. So does added features to UI for Minor, since I agree that UI features is our best analogue to API features mentioned in SemVer. That being said, I am of the opinion that UI changes that make user practices that were possible in the defining Major revision (e.g. 2.0.0) no longer work should also cause major release bumping (for instance the separation of scanning and analysis).

I also fully agree that doing this manually is going to become annoying pretty quickly.
